const version = 'v1'
const prefix = `/api/${version}`

export default {
  headers: {
    authorization: localStorage.getItem('token'),
  },
  system: `${prefix}/system`,
  login: `${prefix}/admin/login`,
  user: `${prefix}/user`,
  refund: `${prefix}/user/refund`,
  upload: `${prefix}/upload`,
  word: `${prefix}/word`,
  deleteWord: `${prefix}/word/delete`,
  uploadWordList: `${prefix}/word/upload`,
  surname: `${prefix}/surname`,
  deleteSurname: `${prefix}/surname/delete`,
  uploadSurname: `${prefix}/surname/upload`,
  couples: `${prefix}/word/couples`,
  addToWordList: `${prefix}/word/couples/addToWordList`,
  uploadCouplesList: `${prefix}/word/couples/upload`,
  deleteCouples: `${prefix}/word/couples/delete`,
  toggleshowable: `${prefix}/word/couples/toggleshowable`,
  wordOutput: `${prefix}/word/output`,
  couplesOutput: `${prefix}/word/couples/output`,
  wordDictionary: `${prefix}/word_dictionary`,
  deleteWordDictionary: `${prefix}/word_dictionary/delete`,
  uploadWordDictionary: `${prefix}/word_dictionary/upload`,
  app: `${prefix}/app`,
  service: `${prefix}/service`,
  feedback: `${prefix}/service/feedback`,
  error: `${prefix}/information/error`,
  classify: `${prefix}/data_dictionary/classify`,
  deleteClassify: `${prefix}/data_dictionary/classify/delete`,
  paymentMethod: `${prefix}/data_dictionary/paymentMethod`,
  deletePaymentMethod: `${prefix}/data_dictionary/paymentMethod/delete`,
  inspiration: `${prefix}/inspiration`,
  deleteInspiration: `${prefix}/inspiration/delete`,
  notification: `${prefix}/notification`,
  deleteNotification: `${prefix}/notification/delete`,
  plan: `${prefix}/plan`,
  deletePlan: `${prefix}/plan/delete`,
  order: `${prefix}/order`,
  deleteOrder: `${prefix}/order/delete`,
  key: `${prefix}/key`,
  deleteKey: `${prefix}/key/delete`,
}
